name: AT Developer Portal
description: Blog
meta_description: "AT Developer Portal Blog"

timezone: Pacific/Auckland
markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /atapi/
domain_name: 'https://janvonbargen.github.io'
google_analytics: 'UA-XXXXXXXX-X'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'https://janvonbargen.github.io/atapi'
author:         'Auckland Transport'
